# Generated by Django 4.1.1 on 2022-09-17 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webby", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 17, 13, 37, 45, 186852, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
